/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax.vistas;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import provemax.accesoADatos.ProductoData;
import provemax.entidades.Producto;

/**
 *
 * @author Enzo Bulacio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        alertaBajoStock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProveedor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMIComprasPorProveedor = new javax.swing.JMenuItem();
        jMenuProveedorPorProducto = new javax.swing.JMenuItem();
        jMenuMasComprados = new javax.swing.JMenuItem();
        jMenuProveedorsPorProducto = new javax.swing.JMenuItem();
        jMenuBajoStock = new javax.swing.JMenu();
        jMenuStockCritico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDPEscritorio.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Prove Max S.R.L.   ");
        jLabel1.setOpaque(true);

        jLLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jDPEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPEscritorio.setLayer(jLLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDPEscritorioLayout = new javax.swing.GroupLayout(jDPEscritorio);
        jDPEscritorio.setLayout(jDPEscritorioLayout);
        jDPEscritorioLayout.setHorizontalGroup(
            jDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDPEscritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jDPEscritorioLayout.setVerticalGroup(
            jDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPEscritorioLayout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuProveedor.setText("Administrar");
        jMenuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProveedorActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Proveedores...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuProveedor.add(jMenuItem1);

        jMenuItem2.setText("Productos...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuProveedor.add(jMenuItem2);

        jMenuBar1.add(jMenuProveedor);

        jMenu2.setText("Compras");

        jMenuItem3.setText("Realizar Compra");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenuConsultas.setText("Consultas");
        jMenuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultasActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Productos Comprados por fecha");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItem4);

        jMIComprasPorProveedor.setText("Compras por Proveedor...");
        jMIComprasPorProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIComprasPorProveedorActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMIComprasPorProveedor);

        jMenuProveedorPorProducto.setText("Productos por Compras...");
        jMenuProveedorPorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProveedorPorProductoActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuProveedorPorProducto);

        jMenuMasComprados.setText("Más Comprados...");
        jMenuMasComprados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMasCompradosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuMasComprados);

        jMenuProveedorsPorProducto.setText("Proveedores por Producto...");
        jMenuProveedorsPorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProveedorsPorProductoActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuProveedorsPorProducto);

        jMenuBar1.add(jMenuConsultas);

        jMenuBajoStock.setText("Productos con bajo Stock");
        jMenuBajoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBajoStockActionPerformed(evt);
            }
        });

        jMenuStockCritico.setText("Stock crítico...");
        jMenuStockCritico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStockCriticoActionPerformed(evt);
            }
        });
        jMenuBajoStock.add(jMenuStockCritico);

        jMenuBar1.add(jMenuBajoStock);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProveedorActionPerformed
       
    }//GEN-LAST:event_jMenuProveedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaProveedor2 vp = new VistaProveedor2();
       vp.setVisible(true);
       jDPEscritorio.add(vp);
       jDPEscritorio.moveToFront(vp);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaProducto vp = new VistaProducto();
       vp.setVisible(true);
       jDPEscritorio.add(vp);
       jDPEscritorio.moveToFront(vp);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaCompra vc = new VistaCompra();
       vc.setVisible(true);
       jDPEscritorio.add(vc);
       jDPEscritorio.moveToFront(vc);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaProductosCompradosPorFecha vpcpf = new VistaProductosCompradosPorFecha();
       vpcpf.setVisible(true);
       jDPEscritorio.add(vpcpf);
       jDPEscritorio.moveToFront(vpcpf);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultasActionPerformed
       
    }//GEN-LAST:event_jMenuConsultasActionPerformed

    private void jMIComprasPorProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIComprasPorProveedorActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaComprasPorProveedor vcpp = new VistaComprasPorProveedor();
       vcpp.setVisible(true);
       jDPEscritorio.add(vcpp);
       jDPEscritorio.moveToFront(vcpp);
    }//GEN-LAST:event_jMIComprasPorProveedorActionPerformed

    private void jMenuMasCompradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMasCompradosActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaMasComprados vmc = new VistaMasComprados();
       vmc.setVisible(true);
       jDPEscritorio.add(vmc);
       jDPEscritorio.moveToFront(vmc);
    }//GEN-LAST:event_jMenuMasCompradosActionPerformed

    private void jMenuProveedorPorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProveedorPorProductoActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaProductosPorCompra ppc = new VistaProductosPorCompra();
       ppc.setVisible(true);
       jDPEscritorio.add(ppc);
       jDPEscritorio.moveToFront(ppc);
    }//GEN-LAST:event_jMenuProveedorPorProductoActionPerformed

    private void jMenuProveedorsPorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProveedorsPorProductoActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaProveedoresPorProducto ppp = new VistaProveedoresPorProducto();
       ppp.setVisible(true);
       jDPEscritorio.add(ppp);
       jDPEscritorio.moveToFront(ppp);
    }//GEN-LAST:event_jMenuProveedorsPorProductoActionPerformed

    private void jMenuStockCriticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStockCriticoActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaProductosConStockBajo pcbs = new VistaProductosConStockBajo();
       pcbs.setVisible(true);
       jDPEscritorio.add(pcbs);
       jDPEscritorio.moveToFront(pcbs);
    }//GEN-LAST:event_jMenuStockCriticoActionPerformed

    private void jMenuBajoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBajoStockActionPerformed
       jDPEscritorio.removeAll();
       jDPEscritorio.repaint();
       VistaProductosConStockBajo pcbs = new VistaProductosConStockBajo();
       pcbs.setVisible(true);
       jDPEscritorio.add(pcbs);
       jDPEscritorio.moveToFront(pcbs);
    }//GEN-LAST:event_jMenuBajoStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        try {
//            FlatArcIJTheme.setup();
//        } catch (Exception ex) {
//            System.err.println("Failed to initialize LaF");
//        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPEscritorio;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMIComprasPorProveedor;
    private javax.swing.JMenu jMenu2;
    private static javax.swing.JMenu jMenuBajoStock;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuMasComprados;
    private javax.swing.JMenu jMenuProveedor;
    private javax.swing.JMenuItem jMenuProveedorPorProducto;
    private javax.swing.JMenuItem jMenuProveedorsPorProducto;
    private javax.swing.JMenuItem jMenuStockCritico;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getjDPEscritorio() {
        return jDPEscritorio;
    }
    
    private void alertaBajoStock() {
        ProductoData prodData = new ProductoData();

        for (Producto p : prodData.listaProductos()) {
            if (p.getStock() <= p.getStockMinimo()) {
                jMenuBajoStock.setBackground(Color.red);
                jMenuBajoStock.setForeground(Color.red);

                Image imagen = new ImageIcon(getClass().getResource("/img/alert.png")).getImage().getScaledInstance(10, 10, java.awt.Image.SCALE_SMOOTH);
                ImageIcon icono = new ImageIcon(imagen);
                jMenuBajoStock.setIcon(icono);
                
                
                Image imagen2 = new ImageIcon(getClass().getResource("/img/inventory.png")).getImage().getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
                ImageIcon logo = new ImageIcon(imagen2);
                jLabel1.setIcon(logo);

            }

        }
    }

}
