/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax.vistas;

import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import provemax.accesoADatos.DetalleCompraData;
import provemax.accesoADatos.ProductoData;
import provemax.entidades.Producto;

/**
 *
 * @author Enzo Bulacio
 */
public class VistaMasComprados extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private DetalleCompraData dcData =  new DetalleCompraData();
    private ProductoData prodData = new ProductoData();
    /**
     * Creates new form VistaMasComprados
     */
    public VistaMasComprados() {
        initComponents();
        cargarIconosAbotnoes();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDCInicio = new com.toedter.calendar.JDateChooser();
        jDCFin = new com.toedter.calendar.JDateChooser();
        jTFCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jBBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Más Comprados");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Más comprados");

        jDCInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDCInicioPropertyChange(evt);
            }
        });

        jDCFin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDCFinPropertyChange(evt);
            }
        });

        jTFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCantidadKeyTyped(evt);
            }
        });

        jLabel2.setText("Cantidad");

        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProductos);

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Desde");

        jLabel4.setText("hasta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDCInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jDCFin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jDCFin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jDCInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDCInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDCInicioPropertyChange
       jDCFin.setMinSelectableDate(jDCInicio.getDate());
    }//GEN-LAST:event_jDCInicioPropertyChange

    private void jDCFinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDCFinPropertyChange
        jDCInicio.setMaxSelectableDate(jDCFin.getDate());
    }//GEN-LAST:event_jDCFinPropertyChange

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTFCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantidadKeyTyped
         String str = jTFCantidad.getText() + evt.getKeyChar();
                if (!str.matches("\\d{0,2}")) {
                    evt.consume();
                }
    }//GEN-LAST:event_jTFCantidadKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private com.toedter.calendar.JDateChooser jDCFin;
    private com.toedter.calendar.JDateChooser jDCInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTable jTProductos;
    // End of variables declaration//GEN-END:variables

     private void asignarIconoABoton (String  ruta, JButton boton){
        Image imagen = new ImageIcon(getClass().getResource(ruta)).getImage().getScaledInstance(22, 22, java.awt.Image.SCALE_SMOOTH);
        ImageIcon icono = new ImageIcon(imagen);

        boton.setIcon(icono);
    }
    
    private void cargarIconosAbotnoes() {
       asignarIconoABoton("/img/search.png", jBBuscar);
       ;
    }
    
    private void inicializarTabla(){
        modeloTabla.setColumnIdentifiers(new Object [] {"Código", "Nombre", "Descripción", "Cantidad"});
        
//        modeloTabla.setRowCount(0);
//        for (Producto p : prodData.listaProductos()) {
//            modeloTabla.addRow(new Object [] {p.getIdProducto(), p.getNombre(), p.getDescripcion(), p.getPrecioActual(),p.getStock()});
//        }
         jTProductos.setModel(modeloTabla);
         jTProductos.setAutoCreateRowSorter(true);
         jTProductos.getColumnModel().getColumn(0).setPreferredWidth(25);
         jTProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
         jTProductos.getColumnModel().getColumn(2).setPreferredWidth(135);
         jTProductos.getColumnModel().getColumn(3).setPreferredWidth(25);
         jTProductos.setDefaultEditor(Object.class, null);
    }

    private void cargarTabla() {

        if (jDCInicio.getDate() != null || jDCFin.getDate() != null) {
            modeloTabla.setRowCount(0);
            LocalDate inicio = jDCInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fin = jDCFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (jTFCantidad.getText().isEmpty()) {
                jTFCantidad.setText("10");
            }

            ArrayList<Integer[]> datos = dcData.listarMasComprados(inicio, fin, Integer.parseInt(jTFCantidad.getText()));

            for (Integer[] d : datos) {
                Producto p = prodData.buscarProductoPorId(d[0].intValue());
                modeloTabla.addRow(new Object[]{p.getIdProducto(), p.getNombre(), p.getDescripcion(), d[1].intValue(), p.getStock()});
            }
        } else {
            JOptionPane.showMessageDialog(this, "No debe haber campos vacíos");
        }
    }
}
