/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax.vistas;

import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import provemax.accesoADatos.ProductoData;
import provemax.entidades.Producto;
import provemax.entidades.Proveedor;

/**
 *
 * @author Enzo Bulacio
 */
public class VistaProducto extends javax.swing.JInternalFrame {
    private ProductoData prodData = new ProductoData();
    private TextAutoCompleter ac;
    ArrayList<Producto> listaProductos = new ArrayList<>(prodData.listaProductos());
    DefaultTableModel modeloTabla = new DefaultTableModel();
    /**
     * Creates new form VistaProduto
     */
    public VistaProducto() {
        initComponents();
        inicializarTabla();
        cargarIconosAbotnoes();
        estadoFormulario(false);
        inicialiarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFPrecioActual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFStock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFIdProducto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jRBEstado = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFStockMinimo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBDesactivar = new javax.swing.JButton();
        jBActivar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTFBusqueda = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Productos");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador de Productos");

        jLabel3.setText("Nombre");

        jLabel4.setText("Descripcion");

        jLabel5.setText("Precio Actual");

        jTFPrecioActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPrecioActualKeyTyped(evt);
            }
        });

        jLabel6.setText("Estado");

        jTFStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFStockKeyTyped(evt);
            }
        });

        jLabel7.setText("Código");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBNuevo.setText("Nuevo Producto");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBGuardar)
                        .addGap(27, 27, 27)
                        .addComponent(jBCancelar)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jBNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRBEstado.setText("Activo?");

        jLabel8.setText("Stock");

        jLabel9.setText("Stoc Minimo");

        jTFStockMinimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFStockMinimoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBEstado)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFDescripcion)
                    .addComponent(jTFNombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFPrecioActual)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTFStock, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jTFIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTFStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBEstado)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jBDesactivar.setText("Desactivar");
        jBDesactivar.setPreferredSize(new java.awt.Dimension(125, 32));
        jBDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesactivarActionPerformed(evt);
            }
        });

        jBActivar.setText("Activar");
        jBActivar.setPreferredSize(new java.awt.Dimension(125, 32));
        jBActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActivarActionPerformed(evt);
            }
        });

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jBDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jBActivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBActivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEditar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTProductos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTProductosFocusGained(evt);
            }
        });
        jTProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTProductosMouseReleased(evt);
            }
        });
        jTProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTProductosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTProductos);

        jLabel2.setText("Buscar");

        jTFBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFBusquedaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFBusqueda))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBusquedaKeyTyped
       
    }//GEN-LAST:event_jTFBusquedaKeyTyped

    private void jTFBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBusquedaKeyReleased
        filtrarProductosPorBusqueda(evt);
    }//GEN-LAST:event_jTFBusquedaKeyReleased

    private void jTProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProductosKeyReleased
       cargarFormularioAlSeleccionarFila();
       ocultarMostrarBotonesBusquda();
    }//GEN-LAST:event_jTProductosKeyReleased

    private void jTProductosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProductosMouseReleased
       cargarFormularioAlSeleccionarFila();
       ocultarMostrarBotonesBusquda();
    }//GEN-LAST:event_jTProductosMouseReleased

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        estadoBusqueda(false);
        estadoFormulario(true);
        jBNuevo.setEnabled(false);
        jTFNombre.requestFocus();
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        estadoBusqueda(false);
        estadoFormulario(true);
        limpiarFormulario();
        jTFIdProducto.setEnabled(false);
        jBNuevo.setEnabled(false);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        limpiarFormulario();
        estadoBusqueda(true);
        estadoFormulario(false);
        jTFBusqueda.requestFocus();
        jTFBusqueda.setText("");
        inicializarTabla();
        jBNuevo.setEnabled(true);
        jTFIdProducto.setEnabled(true);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActivarActionPerformed
        int idProveedor = (int) jTProductos.getValueAt(jTProductos.getSelectedRow(), 0);
        int fila = jTProductos.getSelectedRow();
        prodData.restaurarProducto(idProveedor);
        actualizarListaProductos();
        jTProductos.requestFocus();
        jTProductos.getSelectionModel().setSelectionInterval(fila, fila);
        cargarFormularioAlSeleccionarFila();
    }//GEN-LAST:event_jBActivarActionPerformed

    private void jBDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesactivarActionPerformed
        int idProveedor = (int) jTProductos.getValueAt(jTProductos.getSelectedRow(), 0);
        int fila = jTProductos.getSelectedRow();
        prodData.bajaProducto(idProveedor);
        actualizarListaProductos();
        jTProductos.requestFocus();
        jTProductos.getSelectionModel().setSelectionInterval(fila, fila);
        cargarFormularioAlSeleccionarFila();
    }//GEN-LAST:event_jBDesactivarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
       if(!(jTFNombre.getText().isEmpty() 
           || jTFDescripcion.getText().isEmpty() 
           || jTFPrecioActual.getText().isEmpty() 
           || jTFStock.getText().isEmpty()
           || jTFStockMinimo.getText().isEmpty())){
        
        if (jTFIdProducto.isEnabled()) {
            int fila = jTProductos.getSelectedRow();
            modificarProducto();
            actualizarListaProductos();
            jTProductos.requestFocus();
            jTProductos.getSelectionModel().setSelectionInterval(fila, fila);
            ocultarMostrarBotonesBusquda();
        }else{
            agregarProducto();
            limpiarFormulario();
            actualizarListaProductos();
            jTProductos.requestFocus();
            inicializarTabla();
            jTProductos.getSelectionModel().setSelectionInterval(jTProductos.getRowCount()-1, jTProductos.getRowCount()-1);
        }
       
        estadoBusqueda(true);
        estadoFormulario(false);
        jBNuevo.setEnabled(true);
        jTFIdProducto.setEnabled(true);
       }else {
           JOptionPane.showMessageDialog(this, "No debe haber campos vacíos");
       }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTProductosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTProductosFocusGained
        ocultarMostrarBotonesBusquda();
    }//GEN-LAST:event_jTProductosFocusGained

    private void jTFPrecioActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPrecioActualKeyTyped
        String str = jTFPrecioActual.getText() + evt.getKeyChar();
                if (!str.matches("\\d*\\.?\\d{0,2}")) {
                    evt.consume();
                }
    }//GEN-LAST:event_jTFPrecioActualKeyTyped

    private void jTFStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFStockKeyTyped
         String str = jTFStock.getText() + evt.getKeyChar();
                if (!str.matches("\\d{0,4}")) {
                    evt.consume();
                }
    }//GEN-LAST:event_jTFStockKeyTyped

    private void jTFStockMinimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFStockMinimoKeyTyped
       String str = jTFStockMinimo.getText() + evt.getKeyChar();
                if (!str.matches("\\d{0,4}")) {
                    evt.consume(); 
                }
    }//GEN-LAST:event_jTFStockMinimoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActivar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBDesactivar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFBusqueda;
    private javax.swing.JTextField jTFDescripcion;
    private javax.swing.JTextField jTFIdProducto;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPrecioActual;
    private javax.swing.JTextField jTFStock;
    private javax.swing.JTextField jTFStockMinimo;
    private javax.swing.JTable jTProductos;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
     private void inicializarTabla(){
        modeloTabla.setColumnIdentifiers(new Object [] {"Código", "Nombre", "Descripción", "Precio Actual", "Stock"});
        
        modeloTabla.setRowCount(0);
        for (Producto p : prodData.listaProductos()) {
            modeloTabla.addRow(new Object [] {p.getIdProducto(), p.getNombre(), p.getDescripcion(), p.getPrecioActual(),p.getStock()});
        }
         jTProductos.setModel(modeloTabla);
         jTProductos.setAutoCreateRowSorter(true);
         jTProductos.getColumnModel().getColumn(0).setPreferredWidth(25);
         jTProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
         jTProductos.getColumnModel().getColumn(2).setPreferredWidth(135);
         jTProductos.getColumnModel().getColumn(3).setPreferredWidth(60);
         jTProductos.getColumnModel().getColumn(4).setPreferredWidth(25);
         jTProductos.setDefaultEditor(Object.class, null);
    }

    private void asignarIconoABoton (String  ruta, JButton boton){
        int ancho = boton.getHeight();
        int alto = ancho;
        Image imagen = new ImageIcon(getClass().getResource(ruta)).getImage().getScaledInstance(22, 22, java.awt.Image.SCALE_SMOOTH);
        ImageIcon icono = new ImageIcon(imagen);

        boton.setIcon(icono);
    }
    
    private void cargarIconosAbotnoes() {
       asignarIconoABoton("/img/plus.png", jBNuevo);
       asignarIconoABoton("/img/save.png", jBGuardar);
       asignarIconoABoton("/img/multiply.png", jBCancelar);
       asignarIconoABoton("/img/pen.png", jBEditar);
       asignarIconoABoton("/img/bin.png", jBDesactivar);
       asignarIconoABoton("/img/undo.png", jBActivar);
    }
    
    /////////////////////////////////////////// ADAPTANTDO A PRODUCTO //////////////////////////////////////////////////
    private void filtrarProductosPorBusqueda(java.awt.event.KeyEvent evt){
        modeloTabla.setRowCount(0);
        for (Producto p : listaProductos) {
            if (p.getNombre().toLowerCase().contains(jTFBusqueda.getText().toLowerCase())
                    || p.getDescripcion().toLowerCase().contains(jTFBusqueda.getText().toLowerCase())) {
                modeloTabla.addRow(new Object[]{p.getIdProducto(), p.getNombre(), p.getDescripcion(), p.getPrecioActual(), p.getStock()});
            }
        }
        jTProductos.setModel(modeloTabla);
        
        
        
//        modeloTabla.setRowCount(0);
//        for (Producto p : this.listaProductos){
//            if (p.getNombre().toLowerCase().contains(jTFBusqueda.getText().toLowerCase()) 
//                ||p.getDescripcion().toLowerCase().contains(jTFBusqueda.getText().toLowerCase())){
//                modeloTabla.addRow(new Object[] {p.getIdProducto(), p.getNombre(), p.getDescripcion(), p.getPrecioActual(), p.getStock()});
//            }
//        }
//        jTProductos.setModel(modeloTabla);
    }

    
//    private void filtrar(java.awt.event.KeyEvent evt) {
//        String textoFiltro = "" + evt.getKeyChar();
//
//        if (textoFiltro.isEmpty()) {
//            inicializarTabla();
//        } else {
//
//            for (int i = listaProductos.size() - 1; i >= 0; i--) {
//                String nombre = listaProductos.get(i).getRazonSocial().toString().toLowerCase();
//                if (!nombre.contains(textoFiltro)) {
//                    modeloTabla.removeRow(i);
//                }
//            }
//
//            jTProveedores.setModel(modeloTabla);
//        }
//    }
//    
    private void estadoFormulario(boolean activo){
        if (!activo) {
            jTFIdProducto.setEditable(false);
            jTFNombre.setEditable(false);
            jTFDescripcion.setEditable(false);
            jTFPrecioActual.setEditable(false);
            jTFStock.setEditable(false);
            jTFStockMinimo.setEditable(false);
            jRBEstado.setEnabled(false);
            jBGuardar.setEnabled(false);
            jBCancelar.setEnabled(false);
        } else {
            //jTFIdProveedor.setEditable(true);
            jTFNombre.setEditable(true);
            jTFDescripcion.setEditable(true);
            jTFPrecioActual.setEditable(true);
            jTFStock.setEditable(true);
            jTFStockMinimo.setEditable(true);
            jRBEstado.setEnabled(true);
            jBGuardar.setEnabled(true);
            jBCancelar.setEnabled(true);
        }
    }
    
    private void estadoBusqueda(boolean activo){
        if (!activo) {
            jTFBusqueda.setEditable(false);
            jTProductos.setEnabled(false);
            jBEditar.setEnabled(false);
            jBActivar.setEnabled(false);
            jBDesactivar.setEnabled(false);
        } else {
            jTFBusqueda.setEditable(true);
            jTProductos.setEnabled(true);
            jBEditar.setEnabled(true);
            jBActivar.setEnabled(true);
            jBDesactivar.setEnabled(true);
        }
    }
//    
    private void limpiarFormulario(){
        jTFIdProducto.setText("");
        jTFNombre.setText("");
        jTFDescripcion.setText("");
        jTFPrecioActual.setText("");
        jTFStock.setText("");
        jTFStockMinimo.setText("");
        jRBEstado.setSelected(false);
    }
//    
    private void agregarProducto(){
        Producto producto = new Producto();
        
        producto.setNombre(jTFNombre.getText());
        producto.setDescripcion(jTFDescripcion.getText());
        producto.setPrecioActual(Double.parseDouble(jTFPrecioActual.getText()));
        producto.setStockMinimo(Integer.parseInt(jTFStockMinimo.getText()));
        producto.setStock(Integer.parseInt(jTFStock.getText()));
        producto.setEstado(jRBEstado.isEnabled());
        
        prodData.altaProducto(producto);
    }
//    
     private void modificarProducto(){
         Producto producto = new Producto();

         producto.setIdProducto(Integer.parseInt(jTFIdProducto.getText()));
         producto.setNombre(jTFNombre.getText());
         producto.setDescripcion(jTFDescripcion.getText());
         producto.setPrecioActual(Double.parseDouble(jTFPrecioActual.getText()));
         producto.setStockMinimo(Integer.parseInt(jTFStockMinimo.getText()));
         producto.setStock(Integer.parseInt(jTFStock.getText()));
         producto.setEstado(jRBEstado.isEnabled());

         prodData.modificarProdcuto(producto);
    }
//    
    public void actualizarListaProductos(){
        this.listaProductos = new ArrayList<>(prodData.listaProductos());
    }
//    
    private void inicialiarBotones(){
        jBEditar.setEnabled(false);
        jBActivar.setEnabled(false);
        jBDesactivar.setEnabled(false);
    }
//    
    private void cargarFormularioAlSeleccionarFila(){
         if(jTProductos.getSelectedRow()!=-1 && jTProductos.isEnabled()){
           Producto producto = prodData.buscarProductoPorId((int)jTProductos.getValueAt(jTProductos.getSelectedRow(),0));
           
            jTFIdProducto.setText(String.valueOf(producto.getIdProducto()));
            jTFNombre.setText(producto.getNombre());
            jTFDescripcion.setText(producto.getDescripcion());
            jTFPrecioActual.setText(String.valueOf(producto.getPrecioActual()));
            jTFStock.setText(String.valueOf(producto.getStock()));
            jTFStockMinimo.setText(String.valueOf(producto.getStockMinimo()));
            jRBEstado.setSelected(producto.isEstado());
        }
    }
//    
    private void ocultarMostrarBotonesBusquda(){
        if (jTProductos.getSelectedRow() != -1) {
            jBEditar.setEnabled(true);
//            jBRestaurar.setEnabled(true);
//            jBBorrar.setEnabled(true);
            if (jRBEstado.isSelected()) {
                jBActivar.setEnabled(false);
                jBDesactivar.setEnabled(true);
            } else {
                jBActivar.setEnabled(true);
                jBDesactivar.setEnabled(false);
            }
        }
    }
}
