/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax.vistas;

import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import provemax.accesoADatos.CompraData;
import provemax.accesoADatos.DetalleCompraData;
import provemax.accesoADatos.ProductoData;
import provemax.accesoADatos.ProveedorData;
import provemax.entidades.Compra;
import provemax.entidades.DetalleCompra;
import provemax.entidades.Proveedor;

/**
 *
 * @author Enzo Bulacio
 */
public class VistaComprasPorProveedor extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTablaProveedores = new DefaultTableModel();
    private DefaultTableModel modeloTablaCompras = new DefaultTableModel();
    private DefaultTableModel modeloTablaDC = new DefaultTableModel();
    private DefaultTableModel modeloTablaDCTotal = new DefaultTableModel();
    
    private DefaultComboBoxModel modeloCB = new DefaultComboBoxModel();
    private DetalleCompraData dcData = new DetalleCompraData();
    private ProductoData prodData = new ProductoData();
    private CompraData compraData = new CompraData();
    private ProveedorData provData = new ProveedorData();
    private TextAutoCompleter ac;
    private ArrayList<Proveedor> listaProveedores = new ArrayList<>(provData.listarProveedores());
    
    /**
     * Creates new form VistaComprasPorProveedor
     */
    public VistaComprasPorProveedor() {
        initComponents();
        inicializarTablaProveedores();
        cargarAutoCompleter();
        formatearTablaCompras();
        formatearTablaDetalleCompra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProveedores = new javax.swing.JTable();
        jTFBusqueda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTCompras = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTDetalleCompras = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTDetalleComprasTotal = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Compras por Proveedor");

        jLabel2.setText("Selecciona un Proveedor");

        jTProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTProveedoresMouseReleased(evt);
            }
        });
        jTProveedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTProveedoresKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTProveedores);

        jTFBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBusquedaKeyReleased(evt);
            }
        });

        jTCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTComprasMouseReleased(evt);
            }
        });
        jTCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTComprasKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTCompras);

        jTDetalleCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTDetalleCompras);

        jLabel3.setText("Detalle de Compra");

        jLabel4.setText("Listado de compras");

        jScrollPane4.setBackground(new java.awt.Color(255, 51, 51));
        jScrollPane4.setBorder(null);

        jTDetalleComprasTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTDetalleComprasTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTDetalleComprasTotal.getTableHeader().setResizingAllowed(false);
        jTDetalleComprasTotal.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTDetalleComprasTotal);
        if (jTDetalleComprasTotal.getColumnModel().getColumnCount() > 0) {
            jTDetalleComprasTotal.getColumnModel().getColumn(0).setResizable(false);
            jTDetalleComprasTotal.getColumnModel().getColumn(1).setResizable(false);
            jTDetalleComprasTotal.getColumnModel().getColumn(2).setResizable(false);
            jTDetalleComprasTotal.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(jTFBusqueda))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4))))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBusquedaKeyReleased
        filtrarProveedoresPorBusqueda(evt);
    }//GEN-LAST:event_jTFBusquedaKeyReleased

    private void jTProveedoresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProveedoresMouseReleased
        cargarTablaCompras();
        limpiarTablaDetalle();
    }//GEN-LAST:event_jTProveedoresMouseReleased

    private void jTProveedoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProveedoresKeyReleased
        cargarTablaCompras();
        limpiarTablaDetalle();
    }//GEN-LAST:event_jTProveedoresKeyReleased

    private void jTComprasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTComprasMouseReleased
        cargarTablaDetalleCompras();
    }//GEN-LAST:event_jTComprasMouseReleased

    private void jTComprasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTComprasKeyReleased
        cargarTablaDetalleCompras();
    }//GEN-LAST:event_jTComprasKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTCompras;
    private javax.swing.JTable jTDetalleCompras;
    private javax.swing.JTable jTDetalleComprasTotal;
    private javax.swing.JTextField jTFBusqueda;
    private javax.swing.JTable jTProveedores;
    // End of variables declaration//GEN-END:variables

    private void cargarAutoCompleter(){
        ac = new TextAutoCompleter(jTFBusqueda);
        for (Proveedor p : provData.listarProveedores()){
            ac.addItem(p.getRazonSocial());
        }
    }
    
    private void inicializarTablaProveedores(){
        modeloTablaProveedores.setColumnIdentifiers(new Object [] {"Código", "Razon Social", "Domicilio", "teléfono"});

        
        modeloTablaProveedores.setRowCount(0);
        for (Proveedor p : provData.listarProveedores()) {
            modeloTablaProveedores.addRow(new Object [] {p.getIdProveedor(), p.getRazonSocial(), p.getDomicilio(), p.getTelefono()});
        }
         jTProveedores.setModel(modeloTablaProveedores);
         jTProveedores.getColumnModel().getColumn(0).setPreferredWidth(25);
         jTProveedores.getColumnModel().getColumn(1).setPreferredWidth(100);
         jTProveedores.getColumnModel().getColumn(2).setPreferredWidth(160);
         jTProveedores.getColumnModel().getColumn(3).setPreferredWidth(60);
         jTProveedores.setDefaultEditor(Object.class, null);
    }
    
    private void formatearTablaCompras(){
        modeloTablaCompras.setColumnIdentifiers(new Object [] {"Código", "Fecha"});
            
         jTCompras.setModel(modeloTablaCompras);
         jTCompras.getColumnModel().getColumn(0).setPreferredWidth(25);
         jTCompras.getColumnModel().getColumn(1).setPreferredWidth(75);
         
    }
    
     private void formatearTablaDetalleCompra(){
         DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
         centerRenderer.setHorizontalAlignment(SwingConstants.RIGHT); // Centro
         modeloTablaDC.setColumnIdentifiers(new Object[]{"Código", "Producto", "Cantidad", "Costo", "SubTotal"});
         modeloTablaDCTotal.setColumnCount(5);
         modeloTablaDCTotal.setRowCount(1);
         jTDetalleComprasTotal.setModel(modeloTablaDCTotal);
         jTDetalleComprasTotal.setTableHeader(null);
         jTDetalleComprasTotal.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
         jTDetalleComprasTotal.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);

         jTDetalleCompras.setModel(modeloTablaDC);
         jTDetalleCompras.getColumnModel().getColumn(0).setPreferredWidth(48);
         jTDetalleCompras.getColumnModel().getColumn(1).setPreferredWidth(180);
         jTDetalleCompras.getColumnModel().getColumn(2).setPreferredWidth(90);
         jTDetalleCompras.getColumnModel().getColumn(3).setPreferredWidth(90);
         jTDetalleCompras.getColumnModel().getColumn(4).setPreferredWidth(90);
         jTDetalleCompras.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
         jTDetalleCompras.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
         jTDetalleCompras.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);

         
    }

    private void filtrarProveedoresPorBusqueda(java.awt.event.KeyEvent evt){
        modeloTablaProveedores.setRowCount(0);
        for (Proveedor p : listaProveedores){
            if (p.getRazonSocial().toLowerCase().contains(jTFBusqueda.getText().toLowerCase()) 
                ||p.getTelefono().toLowerCase().contains(jTFBusqueda.getText().toLowerCase())
                ||p.getDomicilio().toLowerCase().contains(jTFBusqueda.getText().toLowerCase())){
                modeloTablaProveedores.addRow(new Object[] {p.getIdProveedor(), p.getRazonSocial(), p.getDomicilio(), p.getTelefono()});
            }
        }
        jTProveedores.setModel(modeloTablaProveedores);
    }
   
    private void cargarTablaCompras(){
        
        modeloTablaCompras.setRowCount(0);
        for (Compra c : compraData.listarComprasPorProveedor((int)jTProveedores.getValueAt(jTProveedores.getSelectedRow(), 0))){
            modeloTablaCompras.addRow(new Object [] {c.getIdCompra(), c.getFecha()});
        }
    }
    
        private void cargarTablaDetalleCompras(){
        double total =0;
        modeloTablaDC.setRowCount(0);
        modeloTablaDCTotal.setRowCount(0);
        for (DetalleCompra dc : dcData.listarDetalleCompraPorCompra((int)jTCompras.getValueAt(jTCompras.getSelectedRow(), 0))){
            modeloTablaDC.addRow(new Object [] {dc.getProducto().getIdProducto(), dc.getProducto().getNombre(), dc.getCantidad(), dc.getPrecioCosto(), ((int)dc.getCantidad() *(double) dc.getPrecioCosto())});
            total +=((int)dc.getCantidad() *(double) dc.getPrecioCosto());
        }
        
        modeloTablaDCTotal.addRow(new Object [] {">>",">>",">>", "TOTAL", total});
        
    }
    
    private void limpiarTablaDetalle(){
        modeloTablaDC.setRowCount(0);
        modeloTablaDCTotal.setRowCount(0);
    }
}
