/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax.vistas;

import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import provemax.accesoADatos.CompraData;
import provemax.accesoADatos.DetalleCompraData;
import provemax.accesoADatos.ProductoData;
import provemax.accesoADatos.ProveedorData;
import provemax.entidades.Producto;
import provemax.entidades.Proveedor;

/**
 *
 * @author Enzo Bulacio
 */
public class VistaProductosCompradosPorFecha extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private DetalleCompraData dcData = new DetalleCompraData();
    private ProductoData prodData = new ProductoData();
    private CompraData compraData = new CompraData();
    private ProveedorData provData = new ProveedorData();
    /**
     * Creates new form VistaProductosCompradosPorFecha
     */
    public VistaProductosCompradosPorFecha() {
        initComponents();
        cargarIconosAbotnoes();
        formatearTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jBBuscar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Productos por Fecha");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos por Fecha");

        jLabel2.setText("Seleccione una Fecha");

        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProductos);

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        cargarTablaPorFecha();
    }//GEN-LAST:event_jBBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProductos;
    // End of variables declaration//GEN-END:variables
    
     private void asignarIconoABoton (String  ruta, JButton boton){
        Image imagen = new ImageIcon(getClass().getResource(ruta)).getImage().getScaledInstance(22, 22, java.awt.Image.SCALE_SMOOTH);
        ImageIcon icono = new ImageIcon(imagen);

        boton.setIcon(icono);
    }
    
    private void cargarIconosAbotnoes() {
       asignarIconoABoton("/img/search.png", jBBuscar);
       ;
    }
    
    
    
    private void formatearTabla(){
        
        
        modeloTabla.setColumnIdentifiers(new Object [] {"Código", "Nombre", "Decripción","Proveedor", "Cantidad", "Costo"});
        
        jTProductos.setModel(modeloTabla);
        
        jTProductos.setAutoCreateRowSorter(true);
        jTProductos.setAlignmentY(CENTER_ALIGNMENT);
        jTProductos.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTProductos.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTProductos.getColumnModel().getColumn(3).setPreferredWidth(40);
        jTProductos.getColumnModel().getColumn(4).setPreferredWidth(50);
        jTProductos.getColumnModel().getColumn(5).setPreferredWidth(40);
        jTProductos.setDefaultEditor(Object.class, null);
    }
    
//    private void cargarTablaPorFecha(){
//        
//        LocalDate fecha = jDCFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//        
//        for (Double[] d : dcData.listaProductosPorFecha(fecha)){
//            
//            int idProducto = d[0].intValue();
//            int cantidadTotal = d[1].intValue();
//            double costoPromedio = d[2];
//            int stockTotal = d[3].intValue();
//
//            Producto p = prodData.buscarProductoPorId(idProducto);
//            
//            modeloTabla.addRow(new Object [] {p.getIdProducto(), p.getNombre(), p.getDescripcion(), 
//                                cantidadTotal, costoPromedio, stockTotal});
//        }
//        jTProductos.setModel(modeloTabla);
//    }
    
    private void cargarTablaPorFecha(){
        modeloTabla.setRowCount(0);
        LocalDate fecha = jDCFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        for (Double[] d : dcData.listaProductosPorFecha(fecha)){
            
            int idProducto = d[0].intValue();
            int idProveedor = d[1].intValue();
            int cantidad = d[2].intValue();
            double precioCosto = d[3];
            

            Producto p = prodData.buscarProductoPorId(idProducto);
            Proveedor prov = provData.buscarProveedorPorId(idProveedor);
            
            modeloTabla.addRow(new Object [] {p.getIdProducto(), p.getNombre(), p.getDescripcion(), 
                                prov.getRazonSocial(), cantidad, precioCosto});
        }
        jTProductos.setModel(modeloTabla);
    }
}
