/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax.vistas;

import javax.swing.table.DefaultTableModel;
import provemax.accesoADatos.ProductoData;
import provemax.entidades.Producto;

/**
 *
 * @author Enzo Bulacio
 */
public class VistaProductosConStockBajo extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTablaProductos = new DefaultTableModel();
    private ProductoData prodData = new ProductoData();
    /**
     * Creates new form VistaProductosConStockBajo
     */
    public VistaProductosConStockBajo() {
        initComponents();
        inicializarTablaProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Productos con bajo Stock");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos con stock por debajo del mínimo");

        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProductos;
    // End of variables declaration//GEN-END:variables

    private void inicializarTablaProductos(){
        modeloTablaProductos.setColumnIdentifiers(new Object [] {"Código", "Nombre", "Descripción", "Precio Actual", "Stock", "Stock Mín."});
        
        modeloTablaProductos.setRowCount(0);
        for (Producto p : prodData.listaProductos()) {
            if(p.getStock()<=p.getStockMinimo()){
                 modeloTablaProductos.addRow(new Object [] {p.getIdProducto(), p.getNombre(), p.getDescripcion(), p.getPrecioActual(),p.getStock(), p.getStockMinimo()});
            }
        }
         jTProductos.setModel(modeloTablaProductos);
         jTProductos.setAutoCreateRowSorter(true);
         jTProductos.getColumnModel().getColumn(0).setPreferredWidth(10);
         jTProductos.getColumnModel().getColumn(1).setPreferredWidth(21);
         jTProductos.getColumnModel().getColumn(2).setPreferredWidth(27);
         jTProductos.getColumnModel().getColumn(3).setPreferredWidth(15);
         jTProductos.getColumnModel().getColumn(4).setPreferredWidth(10);
         jTProductos.getColumnModel().getColumn(5).setPreferredWidth(12);
         jTProductos.setDefaultEditor(Object.class, null);
    }
}
